// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_cw7_git_s33418.Data;

#nullable disable

namespace apbd_cw7_git_s33418.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515215717_AlignWithTutorial7")]
    partial class AlignWithTutorial7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "14-core desktop processor for gaming and productivity.",
                            Name = "Intel Core i5-14600K"
                        },
                        new
                        {
                            Code = "CPU002",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 1,
                            Description = "8-core processor with 3D V-Cache for gaming builds.",
                            Name = "AMD Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Code = "GPU001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 2,
                            Description = "Graphics card for high-refresh 1440p gaming.",
                            Name = "GeForce RTX 4070 Super"
                        },
                        new
                        {
                            Code = "GPU002",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "Graphics card with 16 GB memory for gaming and creation.",
                            Name = "Radeon RX 7800 XT"
                        },
                        new
                        {
                            Code = "RAM001",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 3,
                            Description = "Two 16 GB DDR5 memory modules.",
                            Name = "Corsair Vengeance 32GB DDR5"
                        },
                        new
                        {
                            Code = "SSD001",
                            ComponentManufacturerId = 5,
                            ComponentTypeId = 4,
                            Description = "Fast NVMe SSD for system and project storage.",
                            Name = "Samsung 990 Pro 2TB"
                        },
                        new
                        {
                            Code = "MB001",
                            ComponentManufacturerId = 6,
                            ComponentTypeId = 5,
                            Description = "AM5 motherboard for Ryzen processors.",
                            Name = "ASUS TUF Gaming B650-Plus"
                        },
                        new
                        {
                            Code = "PSU001",
                            ComponentManufacturerId = 7,
                            ComponentTypeId = 6,
                            Description = "750 W modular power supply.",
                            Name = "Seasonic Focus GX-750"
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTL",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVDA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "CRSR",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Gaming, Inc."
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "SMSNG",
                            FoundationDate = new DateTime(1969, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung Electronics Co., Ltd."
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "ASUS",
                            FoundationDate = new DateTime(1989, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "ASUSTeK Computer Inc."
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "SSNC",
                            FoundationDate = new DateTime(1975, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sea Sonic Electronics Co., Ltd."
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Storage Drive"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "MB",
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "PSU",
                            Name = "Power Supply"
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Stock_NonNegative", "[Stock] >= 0");

                            t.HasCheckConstraint("CK_Product_Warranty_NonNegative", "[Warranty] >= 0");

                            t.HasCheckConstraint("CK_Product_Weight_NonNegative", "[Weight] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini",
                            Stock = 18,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Pro",
                            Stock = 7,
                            Warranty = 36,
                            Weight = 9.8f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming X",
                            Stock = 11,
                            Warranty = 36,
                            Weight = 11.4f
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Max",
                            Stock = 4,
                            Warranty = 48,
                            Weight = 13.1f
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "SSD001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "CPU002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "GPU002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "SSD001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "GPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "MB001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "PSU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "CPU002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "GPU001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "RAM001",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "SSD001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "PSU001",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.Component", b =>
                {
                    b.HasOne("apbd_cw7_git_s33418.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_git_s33418.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.PCComponent", b =>
                {
                    b.HasOne("apbd_cw7_git_s33418.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_git_s33418.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_git_s33418.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
